backend:
  name: git-gateway
  branch: main
media_folder: images/uploads
collections:
  - name: "employee"
    label: "Anställda"
    folder: "content/employee"
    create: true
    fields:
      - { label: "Namn", name: "Namn", widget: "string" }
      - { label: "Email", name: "E-post", widget: "string" }
      - { label: "Mobil", name: "phone", widget: "number" }
      - { label: "Bio", name: "bio", widget: "markdown" }
