backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "feat(content): create entry {{path}}"
    update: "feat(content): update entry {{path}}"
    delete: "feat(content): delete entry {{path}}"
media_folder: images/uploads
collections:
  - name: "employee"
    label: "Anställda"
    folder: "content/employee"
    create: true
    slug: "{{name}}-{{email}}"
    fields:
      - name: "name"
        label: "Namn"
        widget: "string"
      - name: "email"
        label: "E-post"
        widget: "string"
      - name: "phone"
        label: "Mobil"
        widget: "string"
      - name: "body"
        label: "Bio"
        widget: "markdown"
